### ISSUE TITLE
Frozen latent space and optimize decoder. 

### ISSUE THREAD

**Issue by boqian-li** [cvlab-epfl/MeshUDF#7]
Hi, I have a question. 
I have trained the autoencoder on several meshes and get the latent spaces of those meshes. Assume i have a mesh A, the latent space of A encoded by encoder is t_a. Not I make some simulation on mesh A (we got mesh A') to add some wrinkles on the surface. And I want to use original t_a as conditional input and finetune the decoder on the simulated mesh A'. I want to know is it possible to use the frozen t_a and optimize the decoder to fit the predicted udf on A'?

**Comment by bguillard** [comment]
Yes, it sounds like a good plan to me!
